esphome:
  name: xmastree
  friendly_name: xmasTree

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "replace_with_rnd_key"

ota:
  - platform: esphome
    password: "replace_with_rnd_pass"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  power_save_mode: none

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Xmastree Fallback Hotspot"
    password: "KC2M07jNRdSJ"

captive_portal:

globals:
  - id: active_effect
    type: int
    restore_value: yes
    initial_value: '0' 
    
binary_sensor:
  - platform: gpio
    id: butMode
    name: "butMode"
    internal: true
    pin:
      number: 14
      mode: INPUT
    filters:
      - invert:
      - delayed_on_off: 10ms
    on_double_click:
      - lambda: !lambda |-
          id(active_effect) += 1;
          auto call = id(leds).turn_on();
          switch (id(active_effect)) {
            case 1:
              call.set_effect("adr_rainbow");
              break;
            case 2:
              call.set_effect("adr_twinkle");
              break;
            case 3:
              call.set_effect("adr_rnd_twinkle");
              break;
            case 4:
              call.set_effect("adr_flicker");
              break;
            case 5:
              call.set_effect("slow_rnd");
              break;
            case 6:
              call.set_effect("techno");
              break;
            case 7:
              call.set_effect("strobe");
              break;
            case 8:
              call.set_effect("flicker");
              break;
            default:
              id(active_effect) = 0;
              call.set_effect("None");
              break;
          }
          call.perform();
    on_click:
      min_length: 750ms
      max_length: 2000ms
      then:
        - if:
            condition:
              - light.is_on: leds
            then:
              - light.turn_off:
                  id: leds
            else:
              - light.turn_on: 
                  id: leds
                  effect:
                    adr_rnd_twinkle

light:
  - platform: fastled_clockless
    id: leds
    name: "leds"
    chipset: WS2812B
    pin: 5
    num_leds: 7
    rgb_order: GRB
    max_refresh_rate: 16ms
    effects: 
      - addressable_rainbow:
          name: "adr_rainbow"
      - addressable_twinkle:
          name: "adr_twinkle"
      - addressable_random_twinkle: 
          name: "adr_rnd_twinkle"
      - addressable_flicker: 
          name: "adr_flicker"
      - random:
          name: "slow_rnd"
          transition_length: 2s
          update_interval: 2s
      - random:
          name: "techno"
          transition_length: 0.1s
          update_interval: 0.1s
      - strobe:
          name: "strobe"
          colors:
            - state: true
              duration: 10ms
              brightness: 100%
            - state: false
              duration: 90ms
      - flicker:
          name: "flicker"
          alpha: 90%
          intensity: 2%